:util-sdk-version: 1.6.1
:toc: macro
:toclevels: 2
:toc-title:
:link-repository: https://github.com/d4l-data4life/hc-util-sdk-kmp
ifdef::env-github[]
:imagesdir: https://github.com/d4l-data4life/hc-util-sdk-kmp/blob/main/assets/images/
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]
ifndef::env-github[]
:imagesdir: assets/images
endif::[]


image::d4l-logo.svg[d4l logo, 150]

[discrete]
= Data4Life Util SDK

This is the Util SDK that provides basic definition and implementation of e.g. Base64, Sha1-hash, MIME types and data size restriction with relating error codes.

link:{link-repository}[*Explore the docs »*]

link:{link-repository}/issues[Report Bug] · link:{link-repository}/issues[Request Feature]


image:https://img.shields.io/badge/Latest-{util-sdk-version}-blueviolet.svg[{util-sdk-version}, link={link-repository}/releases]
image:{link-repository}/workflows/D4L%20CI%20KMP/badge.svg[Build Status, link={link-repository}/actions]
image:https://img.shields.io/badge/Platform-Android%20•%20JVM%20-blue.svg[Platform]
image:https://img.shields.io/badge/license-PRIVATE-lightgrey.svg[License, link=LICENSE]

[discrete]
=== Table Of Contents
toc::[]


== About The Project

The Util SDK is a collection of tools and definitions that are reused across different projects at Data4Life.

=== Features

* Base64 encoding/decoding
* SHA1-HASH calculation
* MIME type helpers
* Logger
* Platform restrictions and error

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]

== Getting Started

=== Requirements

* link:https://adoptopenjdk.net/[Java 8] | link:https://developer.android.com/studio/write/java8-support[Limitations of Java language features and APIs] | https://jakewharton.com/d8-library-desugaring/[Desugaring]
* link:https://kotlinlang.org/[Kotlin 1.4.21]
* Android 6.0 (API 23) to Android 11.0 (API 30)

== Installation

Add the following maven repository url to your root build.gradle:

----
allprojects {
    repositories {
        ...
        maven {
            url = URI("https://maven.pkg.github.com/d4l-data4life/hc-util-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}

----

Your GitHub *username* and *token* needs to be stored in your global Gradle properties: `~/.gradle/gradle.properties`

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token] with `repo`, `write:packages` and `read:packages` scope.

----
gpr.user=github-username
gpr.key=github-token
----

=== Java

Add following dependencies to your app build.gradle.

----
dependencies {
    implementation "care.data4life.hc-util-sdk-kmp:util-jvm:$version"
}
----

=== Android

----
dependencies {
    implementation "care.data4life.hc-util-sdk-kmp:util-android:$version"
}
----

== Roadmap

This project is work in progress. We are working on adding more functionality, guidelines, documentation and other improvements.

== Contributing

You want to help or share a proposal? You have a specific problem? Then open an issue.

=== Contribution Guide

Will be added soon.

=== Development Guide

Will be added soon.

== Copyright and License

Copyright (c) 2020 D4L data4life gGmbH / All rights reserved. Please refer to our link:LICENSE[License] for further details.
