:library_version: 0.0.1
:toc: macro
:toclevels: 2
:toc-title:
ifdef::env-github[]
:imagesdir: https://github.com/d4l-data4life/hc-util-sdk-kmp/blob/main/assets/images/
:link-license: https://github.com/d4l-data4life/hc-util-sdk-kmp/blob/main/LICENSE
:link-contribution: https://github.com/d4l-data4life/hc-util-sdk-kmp/blob/main/CONTRIBUTION.adoc
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]
ifndef::env-github[]
:icons: font
:imagesdir: ./assets/images
:link-license: ./LICENCE
:link-contribution: ./CONTRIBUTION.adoc
endif::[]

++++
<div align="center">
    <!-- PROJECT LOGO -->
    <p>
        <a><img src="https://github.com/d4l-data4life/hc-util-sdk-kmp/blob/main/assets/images/d4l-logo.svg" width="150"/></a>
    </p>
    <!-- PROJECT HEADER -->
    <h1>Util SDK</h1>
    <p><!-- PROJECT DESCRIPTION -->
        This is the Util SDK that provides basic definition and implementation of e.g. Base64, Sha1-hash, MIME types and data size restriction with relating error codes.
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="https://github.com/d4l-data4life/hc-util-sdk-kmp"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/d4l-data4life/hc-util-sdk-kmp/issues">Report Bug</a>
        ·
        <a href="https://github.com/d4l-data4life/hc-util-sdk-kmp/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES -->
        <a href="https://github.com/d4l-data4life/hc-util-sdk-kmp/actions">
            <img src="https://github.com/d4l-data4life/hc-util-sdk-kmp/workflows/D4L%20CI%20KMP/badge.svg" alt="Build Status"/>
        </a>
        <a href="https://github.com/d4l-data4life/hc-util-sdk-kmp/blob/main/LICENSE">
            <img src="https://img.shields.io/badge/license-PRIVATE-blue.svg"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents
toc::[]


== Project setup

Due to currently limitations of the Kotlin Multiplatform project setup
the tests of the specific platforms are extracted into separate modules.

* util – contains the main Kotlin Multiplatform code
* android – module for testing of the android implementation with
instrumentation tests
* jvm – module for testing of the jvm implementation

== Install Gradle

Add the following maven repository url to your root build.gradle:

----
allprojects {
    repositories {
        ...
        maven {
            url = URI("https://maven.pkg.github.com/d4l-data4life/hc-util-sdk-kmp")
            credentials {
                username = project.findProperty("gpr.user") as String? ?: System.getenv("PACKAGE_REGISTRY_USERNAME")
                password = project.findProperty("gpr.key") as String? ?: System.getenv("PACKAGE_REGISTRY_TOKEN")
            }
        }
    }
}

----

Your GitHub *username* and *token* needs to be stored in your global Gradle properties: `~/.gradle/gradle.properties`

NOTICE:: You need to have _read_ access to this repository and generate a https://github.com/settings/tokens/new/[personal access token] with `repo`, `write:packages` and `read:packages` scope.

----
gpr.user=github-username
gpr.key=github-token
----

=== Java

Add following dependencies to your app build.gradle.

----
dependencies {
    implementation "care.data4life.hc-util-sdk-kmp:util-jvm:$version"
}
----

=== Android

----
dependencies {
    implementation "care.data4life.hc-util-sdk-kmp:util-android:$version"
}
----
