name: D4L CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build-and-verify:

    runs-on: ubuntu-latest

    env:
      PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Cleanup
        run: ./gradlew clean
      - name: Build
        run: ./gradlew build

