name: Pull-Request Validation

on:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  pull-request-validation:

    runs-on: [self-hosted, macos]

    env:
      PACKAGE_REGISTRY_USERNAME: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
      PACKAGE_REGISTRY_TOKEN: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}
      GRGIT_USER: ${{ secrets.PACKAGE_REGISTRY_USERNAME }}
      GRGIT_PASS: ${{ secrets.PACKAGE_REGISTRY_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
      - name: Cleanup
        run: ./gradlew clean
      - name: Version
        run: ./gradlew version
      - name: Build
        run: ./gradlew build
      - name: Publish Feature to Maven Repo
        run: ./gradlew publishFeature

